Feature: option to build tcvm without Skia
TotalCross/totalcross pull request #287
Opened 2021-01-26 17:53 UTC by erathke

## Description:
New feature to build TCVM without Skia. 
It's possible to generate a very little final libtcvm (~3MB on Linux). 
It's also now possible to test the VM on OpenBSD.

## Motivation and Context:
Able to use TCVM on OpenBSD.

## Benefited Devices:
 - OS: OpenBSD 6.8

## Tested Devices:
 - OS: Linux Debian 10

2021-01-27 12:51 UTC, acmlira submitted a review, later dismissed
Hello! Hey, first of all, thanks for your contribution! I was going to start reviewing your PR and I came across CI errors:
1) [Commit message error how to solve it?](https://github.com/TotalCross/totalcross/blob/master/CONTRIBUTING.md#commiting)
2) Android build error: I observed in your commit that you changed something in the build files that impacted the Android build. So can you try to solve this problem? If you can't I can help you :sweat_smile:

You can create new commits or simply force push your PR branch we can do squash after approval.

2021-01-27 15:52 UTC, erathke commented
Hi @acmlira ! How are you? I hope you are well.
I did not change the code at that specific place. I got the error and compare with the HEAD and I couldn't find any changes.
If the SKIA_H is defined then the function fadeScreen is available:

nm/ui/gfx_Graphics.c
-----------------------------------------------
#ifdef SKIA_H
// Darkens the screen
static void fadeScreen(Context currentContext, int32 amount) {
    skia_fillRect(0, 0, 0, screen.screenW, screen.screenH,  amount << 24);
    currentContext->dirtyX1 = 0;
    currentContext->dirtyY1 = 0;
    currentContext->dirtyX2 = screen.screenW;
    currentContext->dirtyY2 = screen.screenH;
}
#endif

Please, let me know if you need another action from myself.
Thanks in advance.

Evandro.

2021-01-27 15:57 UTC, teras commented
Maybe the android build was affected because it always requires Skia?

2021-01-27 18:10 UTC, erathke commented
> Maybe the android build was affected because it always requires Skia?
Hi @teras!
By default Skia is enabled, unless defined in cmake (-DUSE_SKIA=OFF).
Android build uses gradle and not cmake...

2021-01-27 20:14 UTC, acmlira commented
We have a native part for Android. This build is called by gradle, underneath, gradle calls CMake to build this big part.

2021-01-27 21:36 UTC, erathke commented
> We have a native part for Android. This build is called by gradle, underneath, gradle calls CMake to build this big part.

Thanks for you the clarification!
I found the issue. I'm working on it.

2021-01-29 14:14 UTC, acmlira commented
Okay, now we just need to adjust the commit :)

2021-01-29 15:59 UTC, erathke commented
> Okay, now we just need to adjust the commit message :)

Hi @acmlira !
What we need for a good commit message? :dagger:

2021-01-29 16:42 UTC, acmlira commented
Here ["Commit message error how to solve it?"](https://github.com/TotalCross/totalcross/blob/master/CONTRIBUTING.md#commiting)  :)

2021-01-29 18:06 UTC, erathke commented
> Here ["Commit message error how to solve it?"](https://github.com/TotalCross/totalcross/blob/master/CONTRIBUTING.md#commiting) :)

What do you think?


feature: option to build tcvm without skia

This feature ables to build TCVM without Skia. By default, this option is ON.
Without Skia, is possible to generate a very little final libtcvm 
(~3MB on Linux).
It's also now possible to test the VM on OpenBSD.
Usage - Disable Skia: cmake <source_dir> -DUSE_SKIA=OFF

2021-01-29 18:09 UTC, acmlira commented
That's it! Thank you very much for your contribution 😄

2021-02-07 16:17 UTC, flsobral commented
OMG I finally took the time to check your PR and understood what you did.
You managed to disable Skia in a way that our legacy drawing operations would work instead. That's really neat!
You're using the original graphical implementation, that nowadays is only used on Windows and Windows CE.
This implementation supports the usage of accelerated graphics (to a certain degree at least), but to use it you must make sure SDL is initialized with a GL context and find a way to share this context with this graphical implementation (while also defining __gl2_h_) and it should work.
Take a look at gfx_Graphics_c.h in the android folder and mainview.m to see how the GL context is initialized on Android and iOS.

The only thing you'll be missing is true type font support, you'll be limited to the tcz fonts.

2021-02-07 18:05 UTC, erathke commented
Thanks @flsobral for your feedback! I think that the acceleration can be implemented in another PR (actually I'm working on it). The target of this PR is to disable Skia and I think that is enough for now, if you agree, of course.
Please, let me know if I need to take another action. :)

2021-03-14 20:39 UTC, erathke commented
Hello @acmlira! How are you?
Will you accept this PR? I ask you because I have others on my queue.
Thanks in advance.
Evandro

2021-04-06 19:49 UTC, flsobral approved these changes

2021-04-06 19:58 UTC, flsobral commented
@erathke could you please rebase your branch on top of our master and squash your commits into a single one?
I'll test the builds for iOS and Windows to accept your PR as soon as you do that. ;)

2021-04-06 19:59 UTC, flsobral requested changes
@erathke could you please rebase your branch on top of our master and squash your commits into a single one?
I'll test the builds for iOS and Windows to accept your PR as soon as you do that. ;)

2021-04-08 00:28 UTC, erathke commented
Hello @flsobral ! Done :D

2021-04-23 12:50 UTC, flsobral approved these changes

2021-04-23 12:50 UTC, VicMisael approved these changes

2021-04-23 12:51 UTC, merged