Removes dependency on old private Sun libraries.
TotalCross/totalcross pull request #83
Opened 2020-07-22 00:08 UTC by flsobral

This is required to build the sdk using latest versions of JDK (JDK 9+?)

## Description:
Describe your changes in details. 

### Related Issue:
 - If you suggest a new feature or change, discuss it first in an issue;
 - If fixing a bug, there should be an issue open describing it with the steps to reproduce.

Please link the issue here.

## Motivation and Context:
Why is this change required? What problem does it solve?

> If it fixes an open issue (different from the previously mentioned), please link to the issue here.

## Benefited Devices:
 - Device: [e.g. Raspberry Pi 3 model b+]
 - OS: [e.g. Linux Raspbian 10]

## How Has This Been Tested?
 - Please describe in detail how you tested your changes;
 - Include details of your testing environment, and the tests you ran to;
 - See how your change affects other areas of the code, etc.

> Don't forget to tell us witch TotalCross version you are using. 

## Tested Devices:
 - Device: [e.g. Raspberry Pi 3 model b+]
 - OS: [e.g. Linux Raspbian 10]

## Screenshots or videos: 
If appropriate.

2020-08-22 16:30 UTC, VaneskaSousa submitted a review, later dismissed

2020-09-16 12:14 UTC, acmlira requested changes
This commit needs to be separated. It is not atomic enough.

2020-09-23 20:10 UTC, acmlira approved these changes

2020-09-23 20:10 UTC, ricardobna approved these changes

2020-09-23 20:21 UTC, merged